# Generated by Django 3.1 on 2020-08-31 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_qualifications_skills_workexperience'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='qualifications',
            table='qualtable',
        ),
        migrations.AlterModelTable(
            name='skills',
            table='skilltable',
        ),
        migrations.AlterModelTable(
            name='workexperience',
            table='worktable',
        ),
    ]
